### ISSUE TITLE
Keyboard casing issue `uppercased` acts like `capsLocked` in text proxies

### ISSUE THREAD

**Issue by amirshane** [KeyboardKit/KeyboardKitPro#1]
I am trying to add additional text fields to a custom keyboard for things like a search bar but am running into an issue with casing. The search text field defaults to `uppercased` but it capitalizes all the letters like `capsLocked` instead of just the first. The ordinary double-tap `capsLocked` works fine and so does the `lowerCased`. This issue only persists in added text proxies so I believe that is where it lies. I've attached a video below.

https://user-images.githubusercontent.com/42124305/125204741-c676d300-e24c-11eb-8827-535843a7fda4.mp4

Looking in KeyboardCasing where the keyboard cases are defined I see the following comment: 
"`.uppercased` should conform to the text proxy's autocapitalization type."
I think the issue might be here, but I'm not sure how exactly to access the text proxy's autocapitalization type or how to set/override it. For reference, I am using the text proxy from: https://gist.github.com/wearhere/f46ab9d837acaeaabfa86a813c44ad25.

**Comment by amirshane** [comment]
Apologies, meant to put this issue in KeyboardKit, just put it there, closing now.

**Comment by danielsaidi** [comment]
Great, thank you!
