### ISSUE TITLE
Hide emoji buttons on keyboard

### ISSUE THREAD

**Issue by HouHangLei** [KeyboardKit/KeyboardKitPro#10]
Hello, the Emoji page we purchased in the Basic version is blank. How can I hide the Emoji button on the keyboard?

I referred to the code for inserting language switching in `DemoLayoutProvider` in the Demo and used the `itemRows.remove(.emoji)` method, but `.emjoi` also needs to enter a parameter, and I don't understand how to use it.

**Comment by danielsaidi** [comment]
Hi @HouHangLei 

Please send an e-mail to info@keyboardkit.com with your license key and I'll take a look.

**Comment by HouHangLei** [comment]
ok i have sent

**Comment by HouHangLei** [comment]
I have found the solution `itemRows.remove(.keyboardType(.emojis))`, thank you for your support!

**Comment by danielsaidi** [comment]
Hi again,

That's great, happy it worked out!

I will take a look at why this happened, so that you will not have to do
this again.

Best

Daniel
