### ISSUE TITLE
i can't integrate keyboardkit pro in my UiKit project 

### ISSUE THREAD

**Issue by Ronik1653** [KeyboardKit/KeyboardKitPro#11]

**Comment by danielsaidi** [comment]
Are you a KeyboardKit Pro user? That is, do you have a license key?

**Comment by Ronik1653** [comment]
i want to modified your project and set it into uikit but i can not modified 
so can you guide me? how can i modified keyboard like you in Uikit ?

**Comment by danielsaidi** [comment]
Sorry, this is a repo for commercial licenses. Please see the public repository and read the docs.

https://github.com/KeyboardKit/KeyboardKit
