### ISSUE TITLE
Hebrew local 'Enter' button interface issue

### ISSUE THREAD

**Issue by ez-ai21** [KeyboardKit/KeyboardKitPro#13]
Current state:
Enter button localized word means "Back".
<img width=350 src="https://github.com/KeyboardKit/KeyboardKitPro/assets/175294009/7cae8e0c-b89f-4527-9191-38061b8e3184" />

Expected state:
Enter button will show the "Enter" symbol.
<img width=350 src="https://github.com/KeyboardKit/KeyboardKitPro/assets/175294009/140ea769-6301-403d-b4ec-2c714cf2852a" />

**Comment by danielsaidi** [comment]
Thank you for noticing this @ez-ai21 - I will fix this in a patch update.

**Comment by danielsaidi** [comment]
This is fixed in the upcoming 8.7.2.
