### ISSUE TITLE
RTL languages long pressing "Space" moves the caret wrongly

### ISSUE THREAD

**Issue by ez-ai21** [KeyboardKit/KeyboardKitPro#14]
Current state:
Gesture swipe to the right at the end of the text does nothing.
Gesture swipe to the right moves the caret left.
Gesture swipe to the left moves the caret right.

https://github.com/KeyboardKit/KeyboardKitPro/assets/175294009/47401758-26fd-43ea-b7ee-6fb4c484d297

Expected result:
Gesture swipe to the right moves caret to the right if possible.
Gesture swipe to the left moves the caret to the left if possible.

**Comment by ez-ai21** [comment]
> Hi @ez-ai21 - does this only behave incorrect in RTL locales?

Correct. 
I believe that the caret movement should behave the same in all languages (RTL and LTR) if it is to align with Apple's approach.

**Comment by danielsaidi** [comment]
Ok got it, thank you! This probably broke once the SDK started applying the primary language correctly. I’ll fix it!

**Comment by danielsaidi** [comment]
This should work in the upcoming 8.7.2
