### ISSUE TITLE
Appstore upload issue: ITMS-90683 issue: NSSpeechRecognitionUsageDescription

### ISSUE THREAD

**Issue by evilutioner** [KeyboardKit/KeyboardKitPro#3]
I was unable to upload to Appstore my application with new version of KeyboardKitPro.

The affected versions: 7.4.1 and 7.5.0
No affected versions: 7.1.3 and 7.2.2

You can’t upload the application to Appstore/Testflight, I get a refusal with the following Appstore message:

We identified one or more issues with a recent delivery for your app, [App Name]. Please correct the following issues, then upload again.

ITMS-90683: Missing purpose string in Info.plist - Your app's code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the "[app name]" bundle should contain a NSSpeechRecognitionUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.

I am not using speech recognition in my app and not want to add to declare it.

**Comment by danielsaidi** [comment]
Hi again @evilutioner

This is strange. I tried removing the required `Info.plist` keys before uploading the app I'm working with, and it still works:

<img width="450" alt="image" src="https://github.com/KeyboardKit/KeyboardKitPro/assets/429927/43c5c09a-74a6-483f-bed1-3f31cdc2090b">

Are you still having this issue?

**Comment by danielsaidi** [comment]
Ok, I have a solution now, where I have extracted the `Speech` framework stuff from the dictation service, which can now be taken out of the library.

This lets us submit apps without adding these keys, unless we actually are using dictation.

Any ideas where I could best place this Speech-specific thing would be greatly appreciated.

**Comment by danielsaidi** [comment]
I am ready to create a first 7.6 release candidate, which will let you try out the updated behavior.

I have tried using it in my upcoming keyboard app, and can now submit to the App Store without the keys. 👍

**Comment by danielsaidi** [comment]
KeyboardKit Pro 7.6 is out now, and fixes this problem. Sorry for the inconvenience!

**Comment by evilutioner** [comment]
@danielsaidi  Awesome, thanks for sorting it out so quickly! Cheers for getting on top of this.

**Comment by danielsaidi** [comment]
@evilutioner Thank you for letting me know about this problem 🙏
