### ISSUE TITLE
Unable to disable autocorrection

### ISSUE THREAD

**Issue by anonys** [KeyboardKit/KeyboardKitPro#9]
Hey! 

I have been trying to disable autocorrection but without any luck although I've set autocorrectionDisabled(true) as seen below - unless I am doing it wrongly.

    SystemKeyboard(
                        state: controller.state,
                        services: controller.services,
                        buttonContent: { $0.view },
                        buttonView: { $0.view },
                        emojiKeyboard: { _ in EmojiKeyboard(
                       state: state,
                        services: services)
                        },
                        toolbar: { _ in }
                       
                    )
                    .autocorrectionDisabled(true)

**Comment by danielsaidi** [comment]
Hi @anonys 

That property is `SwiftUI`-specific and will currently not affect KeyboardKit.

Adding support to disable autocorrect is however in the roadmap.

https://github.com/KeyboardKit/KeyboardKit/issues/667

**Comment by danielsaidi** [comment]
This is supported in `8.1` (with a `8.1.1` bug fix).
